# Experiment Description

This experiment is designed to assess the impact of using contigs predicted as plasmid by **Platon** as seed contigs in **PlasBinFlow**, instead of using the default seeds generated by the **PlasBin** code.

## Requirements for Running PlasBinFlow

### Input File
A CSV file containing rows with information for each sample. Each row must include:
- **Sample ID**
- **GFA file path**
- **GC content file path**
- **GD score file path**
- **Seeds file path**

### Script to Execute
- `plasbin_flow.py`

## Requirements for Running the Evaluation

The input file address should be manually set in `eval.py`. This file should contain:
- **Sample name**
- **GFA path**
- **Ground Truth path**
- **PlasBinFlow Prediction output path**
- **Seeds file path**

### Script for Evaluation
- `eval.py`

## Results

Detailed statistics generated by `eval.py` can be found in **granular_statistics.csv**. 

Key findings:
- **Recall:** Relatively high
- **Precision:**
  - Unweighted: **0.51**
  - Weighted: **0.30**

Despite the high recall, the precision—both weighted and unweighted—is very low. Further analysis is required to identify and address the cause of the low precision.
